# Generated by Django 2.2.7 on 2019-11-30 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBussines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('phone', models.CharField(max_length=200, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Бизнес',
                'verbose_name_plural': 'Бизнесы',
            },
        ),
        migrations.AddField(
            model_name='trichcode',
            name='accessed',
            field=models.BooleanField(default=False, verbose_name='Обработан'),
        ),
        migrations.AddField(
            model_name='trichcode',
            name='lot_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Пластик'), (2, 'Бумага'), (3, 'Железо'), (4, 'Техника'), (5, 'Батарейки'), (6, 'Мебель'), (7, 'Иное')], default=7, verbose_name='Тип мусора'),
        ),
        migrations.AlterField(
            model_name='trichcode',
            name='user_low',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_trichcodes', to='main.UserLow', verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='trichcode',
            name='bussines_buy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bussines_buyed', to='main.UserBussines', verbose_name='Бизнес'),
        ),
    ]
