# Generated by Django 2.2.7 on 2019-11-30 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191130_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trichcode',
            name='bussines_buy',
        ),
        migrations.AddField(
            model_name='trichcode',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='userbussines',
            name='phone',
            field=models.CharField(max_length=200, verbose_name='Почта'),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('took_away', models.BooleanField(default=False, verbose_name='Забрали')),
                ('datetime_send', models.DateTimeField(blank=True, null=True, verbose_name='Дата когда забрали')),
                ('datetime_money_back_1', models.DateTimeField(blank=True, null=True, verbose_name='Дата получения денег жилищниками')),
                ('datetime_money_back_2', models.DateTimeField(blank=True, null=True, verbose_name='Дата получения денег людьми')),
                ('bussines', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bussines_requests', to='main.UserBussines', verbose_name='Бизнес')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.AddField(
            model_name='trichcode',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_trches', to='main.Request', verbose_name='Заявка'),
        ),
    ]
