# Generated by Django 2.2.7 on 2019-11-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191130_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='lot_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Пластик'), (2, 'Бумага'), (3, 'Железо'), (4, 'Техника'), (5, 'Батарейки'), (6, 'Мебель'), (7, 'Иное')], default=7, verbose_name='Тип мусора'),
        ),
    ]
