# Generated by Django 2.2.7 on 2019-11-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_request_lot_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='weight_need',
            field=models.IntegerField(default=500, verbose_name='Вес'),
        ),
    ]
