# Generated by Django 2.2.7 on 2019-11-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_request_weight_need'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='weight_need',
            field=models.IntegerField(default=0, verbose_name='Вес'),
        ),
    ]
