# Generated by Django 2.2.7 on 2019-11-30 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191130_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zhilishniki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назнавание')),
            ],
            options={
                'verbose_name': 'Жилищник',
                'verbose_name_plural': 'Жилищники',
            },
        ),
        migrations.AddField(
            model_name='trichcode',
            name='zh_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zhilishnik_triches', to='main.Zhilishniki', verbose_name='Жилищник'),
        ),
    ]
