# Generated by Django 2.2.7 on 2019-11-30 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_userlow_zh_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trichcode',
            name='zh_id',
        ),
        migrations.AlterField(
            model_name='userlow',
            name='zh_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zhilishnik_users', to='main.Zhilishniki', verbose_name='Жилищник'),
        ),
    ]
