# Generated by Django 2.2.7 on 2019-11-30 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20191130_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlow',
            old_name='fio',
            new_name='name',
        ),
    ]
